package com.hyperbolicbaby.training;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component // ("ExperimentedCommercial")
public class ExperimentedCommercial implements Employee {

    private FinancialReportCreation newReport;

    @Autowired
    public ExperimentedCommercial(FinancialReportCreation newReport) {
        this.newReport = newReport;
    }

    @Override
    public String getTasks() {
        return "Sell, sell, and to keep selling";
    }

    @Override
    public String getReport() {
        // return "Report generated by ExperimentedCommercial";
        return newReport.getFinancialReport();
    }

}
